import 'package:drift/drift.dart';

/// Standalone table for voice/audio notes
/// ARCHITECTURAL CHANGE: No longer extends base Notes table
/// Each note type is now completely independent
@DataClassName('VoiceNoteEntity')
class VoiceNotes extends Table {
  /// Auto-incrementing primary key (for local use only)
  IntColumn get id => integer().autoIncrement()();

  /// Globally unique identifier for cross-device sync
  /// Generated using UUID v4 on creation
  TextColumn get uuid => text().unique()();

  /// Optional title for the note
  TextColumn get title => text().nullable()();

  /// Path to the audio file (local or cloud URL)
  /// Format: local file path or encrypted cloud storage URL
  TextColumn get audioFilePath => text()();

  /// Duration of the audio recording in seconds
  IntColumn get durationSeconds => integer().nullable()();

  /// Optional transcription of the audio content
  /// Generated by speech-to-text service or user-provided
  TextColumn get transcription => text().nullable()();

  /// When the audio was recorded
  /// May differ from createdAt if imported from external source
  DateTimeColumn get recordedAt => dateTime().nullable()();

  /// Whether the note is pinned to the top of the list
  BoolColumn get isPinned => boolean().withDefault(const Constant(false))();

  /// Whether the note is archived (hidden from main view)
  BoolColumn get isArchived => boolean().withDefault(const Constant(false))();

  /// Whether the note is deleted (soft delete)
  /// Deleted notes appear only in trash, not in main views
  BoolColumn get isDeleted => boolean().withDefault(const Constant(false))();

  /// Whether the note has been synced to the cloud
  /// false = needs upload, true = successfully uploaded
  BoolColumn get isSynced => boolean().withDefault(const Constant(false))();

  /// When the note was created
  DateTimeColumn get createdAt => dateTime()();

  /// When the note was last updated
  DateTimeColumn get updatedAt => dateTime()();
}
